version: "3.9"
services:
    php:
        image: mobtitude/php-xdebug:8.0-cli
        entrypoint: ["/usr/local/bin/php"]
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=db
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        depends_on:
            -   mysql
        volumes:
            - ./:/app

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            -   ./data/mysql:/var/lib/mysql
