version: "3.9"
services:
    php:
        image: mobtitude/php-xdebug:8.0-cli
        entrypoint: ["/usr/local/bin/php"]
        env_file:
            -   ./docker/php/env.env
        ports:
            - "9000:9000"
        depends_on:
            -   mysql
        volumes:
            - ./:/app
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            -   ./data/mysql:/var/lib/mysql
